name: mahu_home_services_app
description: "MAHU Booking Platform"

publish_to: "none"

version: 1.0.13+13

environment:
  sdk: ^3.5.4

dependencies:
  awesome_snackbar_content: ^0.1.6
  cached_network_image: ^3.2.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.2.3
  dartz: ^0.10.1
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  intl: ^0.19.0
  flutter_animate: ^1.0.0
  shimmer: ^2.0.0
  flutter_bloc: ^9.1.1
  flutter_map: ^6.1.0
  flutter_map_location_marker: ^8.1.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  latlong2: ^0.9.0
  permission_handler: ^11.3.1
  gap: ^3.0.1
  image_picker: ^1.1.2
  pinput: ^5.0.1
  readmore: ^2.0.0
  shared_preferences: ^2.5.3
  geolocator: ^11.0.1
  smooth_page_indicator: ^1.2.1
  table_calendar: ^3.1.0
  geocoding: ^2.1.1
  intl_phone_field: ^3.2.0

dependency_overrides:
  latlong2: ^0.9.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/imgs/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/landing/
    - assets/imgs/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700


flutter_intl:
  enabled: true


gen-l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: l10n.dart
  output-class: S
  output-dir: lib/generated
